# Generated by Django 5.0.3 on 2024-06-23 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminside", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="basicinfo",
            name="companyname",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
