# Generated by Django 5.0.3 on 2024-07-15 16:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminside", "0002_basicinfo_companyname"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ColorOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Products",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("ProductID", models.BigIntegerField(unique=True)),
                ("ProductCode", models.CharField(max_length=255, unique=True)),
                ("ProductName", models.CharField(max_length=255)),
                (
                    "ProductImage",
                    models.FileField(blank=True, null=True, upload_to="uploads/"),
                ),
                ("CreatedDate", models.DateTimeField(auto_now_add=True)),
                ("UpdatedDate", models.DateTimeField(blank=True, null=True)),
                ("IsFavourite", models.BooleanField(default=False)),
                ("Active", models.BooleanField(default=True)),
                ("HSNCode", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "TotalStock",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        default=0.0,
                        max_digits=20,
                        null=True,
                    ),
                ),
                (
                    "CreatedUser",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_products",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stock", models.PositiveIntegerField()),
                ("sku", models.CharField(max_length=100, unique=True)),
                (
                    "color",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="adminside.coloroption",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="adminside.products",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SizeOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name="BasicInfo",
        ),
        migrations.AddField(
            model_name="productvariant",
            name="size",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="adminside.sizeoption"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="productvariant",
            unique_together={("product", "size", "color")},
        ),
    ]
