# Generated by Django 5.0.3 on 2024-07-16 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("adminside", "0003_coloroption_products_productvariant_sizeoption_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="productvariant",
            unique_together=set(),
        ),
    ]
